[package]
name = "hsc-leaderboard"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.38", features = ["full"] }
axum = { version = "0.7.5", features = ["multipart", "macros"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.68"
axum-macros = "0.4.1"
sqlx = { version = "0.7", features = ["runtime-tokio", "tls-rustls", "any", "postgres", "macros", "chrono"] }
chrono = "0.4.38"
parking_lot = "0.12.3"
rand = { version = "0.8.5", features = ["std_rng"] }
axum-extra = { version = "0.9.3", features = ["typed-header", "cookie"] }
ammonia = "4.0.0"
axum_typed_multipart = "0.11.1"
itertools = "0.13.0"
futures = "0.3.30"
serenity = "0.12"
poise = "0.6.1"
dotenvy = "0.15.7"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-appender = "0.2"
handlebars = { version = "6.0.0", features = ["dir_source"] }
url = "2.5.2"
derive_more = { version = "1", features = ["from", "into"] }
