name: Build

on:
  push:
    branches:
      - main

env:
  # Disable incremental compilation for faster from-scratch builds
  CARGO_INCREMENTAL: 0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup update
      - run: cargo build --release --features embed
      - uses: actions/upload-artifact@v4
        with:
          name: linux
          path: target/release/hsc-leaderboard
